// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260606090018_updb22")]
partial class updb22
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Domain.Entities.Story", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("StoryId");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<string>("BackgroundGradient")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("FontFamily")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("MediaType")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");

                b.Property<string>("MediaUrl")
                    .HasColumnType("TEXT");

                b.Property<string>("TextColor")
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");

                b.Property<string>("TextContent")
                    .HasColumnType("TEXT");

                b.Property<string>("TextPositionX")
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)");

                b.Property<string>("TextPositionY")
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)");

                b.Property<string>("TextStyle")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("ExpiresAt");

                b.HasIndex("UserId");

                b.ToTable("Stories", (string)null);
            });

        modelBuilder.Entity("Domain.Entities.StorySeen", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("StorySeenId");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("SeenAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<long>("StoryId")
                    .HasColumnType("bigint");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.HasIndex("StoryId", "UserId")
                    .IsUnique();

                b.ToTable("StorySeens", (string)null);
            });

        modelBuilder.Entity("Domain.Entities.Story", b =>
            {
                b.HasOne("Domain.Entities.User", "User")
                    .WithMany("Stories")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Domain.Entities.StorySeen", b =>
            {
                b.HasOne("Domain.Entities.Story", "Story")
                    .WithMany()
                    .HasForeignKey("StoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Domain.Entities.User", "User")
                    .WithMany("StorySeens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Story");

                b.Navigation("User");
            });

        modelBuilder.Entity("Domain.Entities.User", b =>
            {
                b.Navigation("Stories");
            });
#pragma warning restore 612, 618
    }
}
